#!/bin/bash -ex
#
# Example Usage:
# BAZALT_INSTALL_PREFIX=/tmp/install BAZALT_PROTOBUF_VERSION=3.15.2 protobuf-source-install.sh

BAZALT_PROTOBUF_VERSION=${BAZALT_PROTOBUF_VERSION:-5.29.5}
BAZALT_PROTOBUF_SOURCE_DIR="/tmp/bazalt/protobuf"
BAZALT_PROTOBUF_BUILD_DIR="/tmp/build/protobuf"
BAZALT_PROTOBUF_WITH_ZLIB=${BAZALT_PROTOBUF_WITH_ZLIB:-"OFF"}
BAZALT_PROTOBUF_BUILD_PROTOC_BINARIES=${BAZALT_PROTOBUF_BUILD_PROTOC_BINARIES:-"OFF"}
BAZALT_PROTOBUF_BUILD_LIBPROTOC=${BAZALT_PROTOBUF_BUILD_LIBPROTOC:-"OFF"}
BAZALT_PROTOBUF_INSTALL=${BAZALT_PROTOBUF_INSTALL:-"ON"}
BAZALT_PROTOBUF_SOURCE_REPOSITORY_URL="https://github.com/protocolbuffers/protobuf"
BAZALT_PROTOBUF_BUILD_SHARED_LIBS=${BAZALT_PROTOBUF_BUILD_SHARED_LIBS:-"OFF"}

BAZALT_INSTALL_PREFIX=${BAZALT_INSTALL_PREFIX:-/usr/local}

echo "Cloning Protobuf version ${BAZALT_PROTOBUF_VERSION}..."
git clone "${BAZALT_PROTOBUF_SOURCE_REPOSITORY_URL}" "${BAZALT_PROTOBUF_SOURCE_DIR}" \
  --depth 1 \
  --branch "v${BAZALT_PROTOBUF_VERSION}" \
  --recurse-submodules

cmake \
  -S "${BAZALT_PROTOBUF_SOURCE_DIR}/${PROTOBUF_SOURCE_CMAKELISTS_DIR}" \
  -B "${BAZALT_PROTOBUF_BUILD_DIR}" \
  -DBUILD_SHARED_LIBS="${BAZALT_PROTOBUF_BUILD_SHARED_LIBS}" \
  -Dprotobuf_WITH_ZLIB="${BAZALT_PROTOBUF_WITH_ZLIB}" \
  -Dprotobuf_BUILD_TESTS=OFF \
  -Dprotobuf_BUILD_EXAMPLES=OFF \
  -Dprotobuf_BUILD_PROTOC_BINARIES="${BAZALT_PROTOBUF_BUILD_PROTOC_BINARIES}" \
  -Dprotobuf_BUILD_LIBPROTOC="${BAZALT_PROTOBUF_BUILD_LIBPROTOC}" \
  -Dprotobuf_INSTALL="${BAZALT_PROTOBUF_INSTALL}" \
  -Dprotobuf_FORCE_FETCH_DEPENDENCIES=ON \
  -DCMAKE_INSTALL_PREFIX="${BAZALT_INSTALL_PREFIX}" \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
cmake --build "${BAZALT_PROTOBUF_BUILD_DIR}" --target install

# Clean up temporary directory
echo "Cleaning up..."
rm -rf "${BAZALT_PROTOBUF_SOURCE_DIR}" "${BAZALT_PROTOBUF_BUILD_DIR}"

echo "Protobuf ${BAZALT_PROTOBUF_VERSION} installed successfully to ${BAZALT_INSTALL_PREFIX}."
