name: buildah-build-protobuf
on:
  workflow_dispatch:
  push:
    paths:
      - containers/bazalt-protobuf/**
      - containers/scripts/protobuf-install.sh
      - .github/workflows/buildah-build-protobuf.yml # Self-trigger

env:
  REGISTRY: ghcr.io/bounverif
  IMAGE_NAME: bazalt
  HOSTARCH: amd64
  PLATFORM: linux-amd64
  PROTOBUF_VERSION: 3.21.12
  PROTOBUF_LATEST_VERSION: 5.29.3 # TODO: Update this value programmatically

permissions:
  contents: read
  packages: write

jobs:
  buildah-build:
    name: Build container images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        version: ["3.21.12", "5.29.3"]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.version }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
      - name: Install container tools
        run: sudo apt-get install podman buildah jq

      - name: Prepare environment variables
        run: |
          echo "HOSTARCH=$(podman info --format='{{.Host.Arch}}')" >> $GITHUB_ENV
          echo "PLATFORM=$(podman info --format='{{.Version.OsArch}}' | sed 's/\//-/g')" >> $GITHUB_ENV
          echo "PROTOBUF_VERSION=${{ matrix.version }}" >> $GITHUB_ENV
          if [ "${{ env.PROTOBUF_VERSION }}" == "latest" ]; then
            echo "PROTOBUF_VERSION=${PROTOBUF_LATEST_VERSION}" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build protobuf container image
        id: build-protobuf
        uses: redhat-actions/buildah-build@v2
        with:
          context: ./containers
          image: bazalt
          tags: |
            ${{ env.PROTOBUF_VERSION }}-protobuf
            ${{ env.PROTOBUF_VERSION }}-protobuf-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            BAZALT_BUILD_PROTOBUF_VERSION=${{ env.PROTOBUF_VERSION }}
          extra-args: |
            --target bazalt-protobuf
          containerfiles: |
            ./containers/bazalt-protobuf/Dockerfile

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-protobuf-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-protobuf.outputs.image }}
          tags: ${{ env.PROTOBUF_VERSION }}-protobuf-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-devel-${{ env.PROTOBUF_VERSION }}-${{ env.PLATFORM }}

      - name: Upload digests
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ env.PROTOBUF_VERSION }}-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digest-*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0 # no compression

  buildah-merge:
    name: Merge container images
    runs-on: ubuntu-24.04
    needs: buildah-build
    strategy:
      fail-fast: false
      matrix:
        version: ["3.21.12", "5.29.3"]
    if: github.ref == 'refs/heads/main' && always()
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-*
          merge-multiple: true

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment variables
        run: |
          echo "PROTOBUF_VERSION=${{ matrix.version }}" >> $GITHUB_ENV
          if [ "${{ env.PROTOBUF_VERSION }}" == "latest" ]; then
            echo "PROTOBUF_VERSION=${PROTOBUF_LATEST_VERSION}" >> $GITHUB_ENV
          fi

      - name: Create and push manifest list for multi-arch images
        run: |
          MANIFEST=bazalt-protobuf
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-devel-${{ env.PROTOBUF_VERSION }}-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.PROTOBUF_VERSION }}-protobuf
          if [ "${{ env.PROTOBUF_VERSION }}" == "${{ env.PROTOBUF_LATEST_VERSION }}" ]; then
            buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-protobuf
          fi
