name: buildah-build-zenoh
on:
  workflow_dispatch:
  push:
    paths:
      - containers/bazalt-zenoh/**
      - .github/workflows/buildah-build-zenoh.yml # Self-trigger

env:
  REGISTRY: ghcr.io/bounverif
  IMAGE_NAME: bazalt-zenoh
  HOSTARCH: amd64
  PLATFORM: linux-amd64
  ZENOH_VERSION: latest
  ZENOH_LATEST_VERSION: latest

permissions:
  contents: read
  packages: write

jobs:
  buildah-build:
    name: Build container images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
      - name: Install container tools
        run: sudo apt-get install podman buildah jq

      - name: Prepare environment variables
        run: |
          echo "HOSTARCH=$(podman info --format='{{.Host.Arch}}')" >> $GITHUB_ENV
          echo "PLATFORM=$(podman info --format='{{.Version.OsArch}}' | sed 's/\//-/g')" >> $GITHUB_ENV
          if [ "${{ env.ZENOH_VERSION }}" == "latest" ]; then
            echo "ZENOH_VERSION=$(curl -sL "https://api.github.com/repos/eclipse-zenoh/zenoh-pico/releases/latest" | jq -r '.tag_name' )" >> $GITHUB_ENV
          fi
          echo "ZENOH_LATEST_VERSION=$(curl -sL "https://api.github.com/repos/eclipse-zenoh/zenoh-pico/releases/latest" | jq -r '.tag_name'd )" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Zenoh container image
        id: build-zenoh-devel
        uses: redhat-actions/buildah-build@v2
        with:
          context: ./containers
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.ZENOH_VERSION }}-devel
            ${{ env.ZENOH_VERSION }}-devel-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            BAZALT_BUILD_ZENOH_VERSION=${{ env.ZENOH_VERSION }}
          extra-args: |
            --target bazalt-zenoh-devel
          containerfiles: |
            ./containers/bazalt-zenoh/Dockerfile

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-zenoh-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-zenoh-devel.outputs.image }}
          tags: ${{ env.ZENOH_VERSION }}-devel-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-devel-${{ env.ZENOH_VERSION }}-${{ env.PLATFORM }}

      - name: Upload digests
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ env.ZENOH_VERSION }}-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digest-*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0 # no compression

  buildah-merge:
    name: Merge container images
    runs-on: ubuntu-24.04
    needs: buildah-build
    if: github.ref == 'refs/heads/main' && always()
    steps:
      # - run: mkdir -p $TMPDIR
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-*
          merge-multiple: true

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment variables
        run: |
          if [ "${{ env.ZENOH_VERSION }}" == "latest" ]; then
            echo "ZENOH_VERSION=$(curl -sL "https://api.github.com/repos/eclipse-zenoh/zenoh-pico/releases/latest" | jq -r '.tag_name' )" >> $GITHUB_ENV
          fi
          echo "ZENOH_LATEST_VERSION=$(curl -sL "https://api.github.com/repos/eclipse-zenoh/zenoh-pico/releases/latest" | jq -r '.tag_name'd )" >> $GITHUB_ENV

      - name: Create and push manifest list for multi-arch images
        run: |
          MANIFEST=bazalt-zenoh
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-devel-${{ env.ZENOH_VERSION }}-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.ZENOH_VERSION }}-devel
          if [ "${{ env.ZENOH_VERSION }}" == "${{ env.ZENOH_LATEST_VERSION }}" ]; then
            buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-devel
          fi
